spring:
  datasource:    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useSSL=true    driver-class-name: com.mysql.cj.jdbc.Driver    data-username: root
    data-password: root
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp

