spring:
  datasource:    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useSSL=true    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root#    data-username: root
#    data-password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
      
