spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test_schema1?serverTimezone=Asia/Shanghai&useSSL=true
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
#    show-sql: true
logging:
  level:
    root: error
    com.yao.demo: warn
  file: spring-boot-logger/island-training
    

