spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test1?serverTimezone=Asia/Shanghai&useSSL=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
logging:
  level:
    root: error
    com.yao.demo: info
  file: devlog/my.log
    

